name: Validate pipeline

on:
  push: 

jobs:
  test-codebase:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install pip, setuptools, and wheel
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dev dependencies
      run: |
        export PATH=$PATH:$HOME/.local/bin
        make install

    - name: Run tests and validation
      run: |
        export PATH=$PATH:$HOME/.local/bin
        make validate
